# Generated by Django 2.1.5 on 2019-02-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='TMP',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='text',
            new_name='antenna',
        ),
        migrations.RemoveField(
            model_name='request',
            name='result',
        ),
        migrations.AddField(
            model_name='request',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Status'),
        ),
    ]
