# Generated by Django 2.1.5 on 2019-03-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_antennes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='path_to_gga',
            new_name='path_to_pdf',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='path_to_rtk',
            new_name='path_to_scv',
        ),
    ]
