# Generated by Django 2.1.5 on 2019-03-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190322_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='path_to_scv',
            new_name='path_to_csv',
        ),
    ]
